config/routes.rb
Rails.application.routes.draw do

  get 'blogs/quick' => 'blogs#quick_create'

  post 'blogs/quick' => 'blogs#quick_post'

  get 'blogs/quick/:url' => 'blogs#quick_show'

  resources :blogs do
    resources :posts
  end

  root "blogs#index"

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @photos = []
    unless @blog = Blog.find_by(id: params[:id])
      @blog = { url: params[:id] }
    end
    posts = HTTParty.post("https://api.tumblr.com/v2/blog/#{@blog.url}/posts?api_key=z3lrerYuy075yp74piNFYOInINGoxNk1jTMWd8YlrJTUxqNfB7").parsed_response['response']['posts']
    posts.each do |post|
      begin
        post['photos'].each do |photo|
          @photos << photo['alt_sizes'][0]['url']
        end
      rescue
        puts "PHOTO ERROR"
      end
    end
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def quick_create
    render 'quick.html'
  end

  def quick_post
    redirect_to blogs
  end

  def quick_show
    @photos = []
    @blog = Blog.new(title: "QUICK BLOG", url: params[:url])
    posts = HTTParty.post("https://api.tumblr.com/v2/blog/#{@blog.url}/posts?api_key=z3lrerYuy075yp74piNFYOInINGoxNk1jTMWd8YlrJTUxqNfB7").parsed_response['response']['posts']
    posts.each do |post|
      post['photos'].each do |photo|
        @photos << photo['alt_sizes'][0]['url']
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :url)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:post_id, :post_url, :blog_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.url %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/quick.html.erb
<form action="/blogs/quick" method="POST">
	<input type="text" id="URL" placeholder="URL" />
	<input type="submit" value="SLIDESHOW" >
</form>

app/views/blogs/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset='UTF-8'>

	<title>Simple jQuery Slideshow</title>

<!-- 	<link rel='stylesheet' href='css/style.css'> -->

	<style>
/*		#slideshow {
		    margin: 80px auto;
		    position: relative;
		    width: 240px;
		    height: 240px;
		    padding: 10px;
		    box-shadow: 0 0 20px rgba(0,0,0,0.4);
		}*/

		#slideshow > div {
		    position: absolute;
		    top: 10px;
		    left: 10px;
		    right: 10px;
		    bottom: 10px;
		}
	</style>

<!--	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script> -->
	<script>
		$(function() {

			$("#slideshow > div:gt(0)").hide();

			var delaySlider = $("#delay");

			setInterval(function() {
			  $('#slideshow > div:first')
			    .fadeOut(1000)
			    .next()
			    .fadeIn(1000)
			    .end()
			    .appendTo('#slideshow');

			    console.log((delaySlider.val() * 1000))

			},  (delaySlider.val() * 1000));

		});

		$(function() {
		   $( "#slider" ).slider();
		 });
	</script>
</head>

<body>

	<!-- SOURCE: https://css-tricks.com/examples/SimpleSlideshow/ -->
	<div id="slideshow">
		<% @photos.each do |photo| %>
			<div>
				<img src="<%= photo %>" alt="">
				<div id="slider"></div>
			</div>
		<% end %>
		<!-- SOURCE: http://www.w3schools.com/jquerymobile/jquerymobile_form_sliders.asp -->

	</div>
	<div id='delay-box'>
		<p><input type="range" name="delay" id="delay" value="6" min="1" max="10" /></p>
	</div>
 <style type="text/css" style="display: none !important;">
	* {
		margin: 0;
		padding: 0;
	}
	body {
		overflow-x: hidden;
	}
	#delay-box {
		position: fixed;
		bottom: 0px;
		width: 100%;
		background: white;
	}#delay {
		width: 100%
	}
</style>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sumrslt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :post_url %><br>
    <%= f.text_field :post_url %>
  </div>
  <div class="field">
    <%= f.label :blog_id %><br>
    <%= f.text_field :blog_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Post url</th>
      <th>Blog</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.post_id %></td>
        <td><%= post.post_url %></td>
        <td><%= post.blog_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @post.post_id %>
</p>

<p>
  <strong>Post url:</strong>
  <%= @post.post_url %>
</p>

<p>
  <strong>Blog:</strong>
  <%= @post.blog_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>